export const data = {
  sections: [
    {
      name: "Design & Creativity",
      roles: [
        "Designer",
        "3D Artist",
        "Architect",
        "Photographer",
        "Musician",
        "Video Editor"
      ],
      websites: [
        "https://www.figma.com",
        "https://www.canva.com",
        "https://dribbble.com",
        "https://www.behance.net",
        "https://www.sketch.com",
        "https://www.adobe.com/creativecloud.html",
        "https://www.coreldraw.com",
        "https://affinity.serif.com",
        "https://www.invisionapp.com",
        "https://uizard.io",
        "https://unsplash.com",
        "https://www.freepik.com",
        "https://elements.envato.com",
        "https://www.flaticon.com",
        "https://coolors.co",
        "https://lottiefiles.com",
        "https://icons8.com",
        "https://www.archdaily.com",
        "https://www.autodesk.com",
        "https://www.rhino3d.com",
        "https://www.blender.org",
        "https://www.artstation.com",
        "https://www.deviantart.com",
        "https://soundcloud.com",
        "https://www.bandlab.com",
        "https://splice.com",
        "https://www.finalcutpro.com",
        "https://www.kapwing.com"
      ]
    },
    {
      name: "Academic & Research",
      roles: [
        "Student",
        "Teacher",
        "Researcher",
        "Scientist",
        "Doctor",
        "Lawyer"
      ],
      websites: [
        "https://scholar.google.com",
        "https://www.jstor.org",
        "https://www.khanacademy.org",
        "https://www.coursera.org",
        "https://www.edx.org",
        "https://www.udemy.com",
        "https://ocw.mit.edu",
        "https://plato.stanford.edu",
        "https://www.nature.com",
        "https://www.sciencedirect.com",
        "https://pubmed.ncbi.nlm.nih.gov",
        "https://www.springer.com",
        "https://eric.ed.gov",
        "https://quizlet.com",
        "https://chegg.com",
        "https://www.researchgate.net",
        "https://www.academia.edu",
        "https://wolframalpha.com",
        "https://www.britannica.com",
        "https://www.cambridge.org",
        "https://www.oxfordlearnersdictionaries.com",
        "https://dictionary.cambridge.org",
        "https://law.cornell.edu",
        "https://heinonline.org",
        "https://jamanetwork.com",
        "https://www.medscape.com",
        "https://bmj.com",
        "https://ieee.org",
        "https://aps.org",
        "https://royalsociety.org"
      ]
    },
    {
      name: "Programming & Tech",
      roles: [
        "Developer",
        "AI/ML Engineer",
        "Data Analyst",
        "Cybersecurity Specialist",
        "Engineer"
      ],
      websites: [
        "https://github.com",
        "https://gitlab.com",
        "https://stackoverflow.com",
        "https://codepen.io",
        "https://jsfiddle.net",
        "https://codesandbox.io",
        "https://replit.com",
        "https://vscode.dev",
        "https://developer.mozilla.org",
        "https://w3schools.com",
        "https://devdocs.io",
        "https://freecodecamp.org",
        "https://leetcode.com",
        "https://codeforces.com",
        "https://geeksforgeeks.org",
        "https://hackerrank.com",
        "https://kaggle.com",
        "https://css-tricks.com",
        "https://smashingmagazine.com",
        "https://python.org",
        "https://nodejs.org",
        "https://react.dev",
        "https://angular.io",
        "https://vuejs.org",
        "https://svelte.dev",
        "https://nextjs.org",
        "https://deno.land",
        "https://graphql.org",
        "https://supabase.com",
        "https://owasp.org"
      ]
    },
    {
      name: "Business & Management",
      roles: [
        "Entrepreneur",
        "Manager",
        "Consultant",
        "Project Manager",
        "HR Specialist",
        "Salesperson",
        "Investor",
        "Trader",
        "Accountant"
      ],
      websites: [
        "https://www.linkedin.com",
        "https://www.glassdoor.com",
        "https://www.indeed.com",
        "https://www.slack.com",
        "https://www.trello.com",
        "https://asana.com",
        "https://monday.com",
        "https://notion.so",
        "https://clickup.com",
        "https://hubspot.com",
        "https://salesforce.com",
        "https://zoho.com",
        "https://quickbooks.intuit.com",
        "https://xero.com",
        "https://waveapps.com",
        "https://investopedia.com",
        "https://bloomberg.com",
        "https://wsj.com",
        "https://tradingview.com",
        "https://robinhood.com",
        "https://etoro.com",
        "https://fidelity.com",
        "https://forbes.com",
        "https://hbr.org",
        "https://coursera.org/business",
        "https://ycombinator.com",
        "https://angel.co",
        "https://crunchbase.com",
        "https://gartner.com",
        "https://statista.com"
      ]
    },
    {
      name: "Marketing & Communication",
      roles: [
        "Marketer",
        "Writer",
        "Journalist",
        "Translator",
        "Content Creator"
      ],
      websites: [
        "https://mailchimp.com",
        "https://buffer.com",
        "https://hootsuite.com",
        "https://sproutsocial.com",
        "https://semrush.com",
        "https://ahrefs.com",
        "https://moz.com",
        "https://neilpatel.com/ubersuggest",
        "https://medium.com",
        "https://substack.com",
        "https://wordpress.com",
        "https://wix.com",
        "https://squarespace.com",
        "https://weebly.com",
        "https://problogger.com",
        "https://grammarly.com",
        "https://hemingwayapp.com",
        "https://deepl.com",
        "https://translate.google.com",
        "https://quillbot.com",
        "https://pocket.com",
        "https://buzzfeed.com",
        "https://nytimes.com",
        "https://guardian.com",
        "https://wired.com",
        "https://cnbc.com",
        "https://theverge.com",
        "https://youtube.com",
        "https://tiktok.com",
        "https://patreon.com"
      ]
    },
    {
      name: "Gaming & Entertainment",
      roles: [
        "Gamer",
        "Streamer",
        "Coach",
        "Athlete"
      ],
      websites: [
        "https://store.steampowered.com",
        "https://epicgames.com",
        "https://gog.com",
        "https://ubisoft.com",
        "https://ea.com",
        "https://xbox.com",
        "https://playstation.com",
        "https://nintendo.com",
        "https://twitch.tv",
        "https://youtube.com/gaming",
        "https://discord.com",
        "https://obsproject.com",
        "https://streamlabs.com",
        "https://xsplit.com",
        "https://ign.com",
        "https://gamespot.com",
        "https://polygon.com",
        "https://pcgamer.com",
        "https://metacritic.com/game",
        "https://esports.com",
        "https://hltv.org",
        "https://chess.com",
        "https://lichess.org",
        "https://strava.com",
        "https://nike.com",
        "https://adidas.com",
        "https://bodybuilding.com",
        "https://menshealth.com",
        "https://womenshealthmag.com",
        "https://espn.com"
      ]
    }
  ]
};
